app:
    resource: '@ProductBundle/Controller/'
    type: annotation

#Category Entity routes
category.index:
    path: /category/{page}
    defaults: { _controller: ProductBundle:Product:index }
    requirements:
        page: '\d+'

category.create:
    path: /category/create
    defaults: { _controller: ProductBundle:Product:create }

category.edit:
    path: /edit/{id}
    defaults: { _controller: ProductBundle:Product:edit }

category.delete:
    path: /delete/{id}
    defaults: { _controller: ProductBundle:Product:delete }